'use client';

import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { translate as t } from '@/i18n/translate';
import { timeAgo } from '@/lib/core/dates';
import { api } from '@/lib/client/api';
import type { Notification } from '@/lib/domain/types';
import { Icon, type IconName } from '@/components/ui/Icon';
import { Button, EmptyState } from '@/components/ui/primitives';
import { cx } from '@/components/ui/cx';

/**
 * Notification feed.
 *
 * Notifications are generated by the booking, messaging and review services,
 * so this only has to render and mark them read.
 */

const KIND_ICON: Record<Notification['kind'], IconName> = {
  booking: 'tag',
  message: 'message',
  review: 'star-empty',
  payout: 'wallet',
  system: 'info',
};

export function NotificationList({ notifications: initial }: { notifications: Notification[] }) {
  const router = useRouter();
  const [notifications, setNotifications] = useState(initial);
  const [busy, setBusy] = useState(false);

  const unread = notifications.filter((n) => !n.readAt).length;

  const markAll = async () => {
    setBusy(true);
    const now = new Date().toISOString();
    // Optimistic — a failed write only means the badge is briefly wrong.
    setNotifications((current) => current.map((n) => ({ ...n, readAt: n.readAt ?? now })));
    try {
      await api.post('/api/notifications', { all: true });
      router.refresh();
    } finally {
      setBusy(false);
    }
  };

  const markOne = async (id: string) => {
    setNotifications((current) =>
      current.map((n) => (n.id === id ? { ...n, readAt: n.readAt ?? new Date().toISOString() } : n)),
    );
    await api.post('/api/notifications', { id }).catch(() => {});
    router.refresh();
  };

  if (!notifications.length) {
    return <EmptyState icon="bell" title={t('navigation', 'notifications')} body={t('general', 'notAvailable')} />;
  }

  return (
    <>
      {unread > 0 ? (
        <div className="mb-3 flex justify-end">
          <Button variant="ghost" size="sm" onClick={markAll} loading={busy}>
            {t('inbox', 'markAsRead')}
          </Button>
        </div>
      ) : null}

      <ul className="divide-y divide-line overflow-hidden rounded-card border border-line bg-white">
        {notifications.map((notification) => {
          const body = (
            <>
              <span
                className={cx(
                  'flex h-9 w-9 shrink-0 items-center justify-center rounded-full',
                  notification.readAt ? 'bg-surface-sunken text-ink-muted' : 'bg-brand-50 text-brand-700',
                )}
              >
                <Icon name={KIND_ICON[notification.kind]} size={17} />
              </span>
              <span className="min-w-0 flex-1">
                <span
                  className={cx(
                    'block text-sm',
                    notification.readAt ? 'font-medium text-ink-soft' : 'font-bold text-ink',
                  )}
                >
                  {notification.title}
                </span>
                <span className="mt-0.5 block text-sm text-ink-muted">{notification.body}</span>
                <span className="mt-1 block text-xs text-ink-faint">{timeAgo(notification.createdAt)}</span>
              </span>
              {!notification.readAt ? (
                <span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-brand-600" aria-label={t('inbox', 'unread')} />
              ) : null}
            </>
          );

          return (
            <li key={notification.id}>
              {notification.href ? (
                <Link
                  href={notification.href}
                  onClick={() => markOne(notification.id)}
                  className="flex items-start gap-3 p-3 transition-colors hover:bg-surface-sunken"
                >
                  {body}
                </Link>
              ) : (
                <button
                  type="button"
                  onClick={() => markOne(notification.id)}
                  className="flex w-full items-start gap-3 p-3 text-left transition-colors hover:bg-surface-sunken"
                >
                  {body}
                </button>
              )}
            </li>
          );
        })}
      </ul>
    </>
  );
}
